AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Cloudformation template to create IAM Roles for use with Task Definition
  taskRoleArn values

Resources:

  s3photosappphotostorage:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  s3photosappwebclient:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

Outputs:

  s3photosappphotostorage:
    Description: s3photosappphotostorage taskRoleArn
    Value: !GetAtt
      - s3photosappphotostorage
      - Arn

  s3photosappwebclient:
    Description: s3photosappwebclient taskRoleArn
    Value: !GetAtt
      - s3photosappwebclient
      - Arn